// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Sora.Store.Warehouse
{
    /// <summary>
    /// Bảng lưu thông tin của category
    /// </summary>
    public partial class Category
    {
        public Category()
        {
            Product = new HashSet<Product>();
            Tag = new HashSet<Tag>();
        }

        /// <summary>
        /// Id của category
        /// </summary>
        public Guid Id { get; set; }
        /// <summary>
        /// Tên của category
        /// </summary>
        public string Title { get; set; }
        /// <summary>
        /// Slug của category
        /// </summary>
        public string Slug { get; set; }
        /// <summary>
        /// Nội dung của category (mô tả, giới thiệu,...)
        /// </summary>
        public string Content { get; set; }
        /// <summary>
        /// Thời gian tạo
        /// </summary>
        public DateTime CreatedDate { get; set; }
        /// <summary>
        /// Thời gian cập nhật
        /// </summary>
        public DateTime? UpdatedDate { get; set; }

        public virtual ICollection<Product> Product { get; set; }
        public virtual ICollection<Tag> Tag { get; set; }
    }
}