// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Sora.Store.Warehouse
{
    /// <summary>
    /// Bảng lưu thông tin của tag
    /// </summary>
    public partial class Tag
    {
        public Tag()
        {
            Producttag = new HashSet<Producttag>();
        }

        /// <summary>
        /// Id của tag
        /// </summary>
        public Guid Id { get; set; }
        /// <summary>
        /// Tên của tag
        /// </summary>
        public string Title { get; set; }
        /// <summary>
        /// Slug của tag
        /// </summary>
        public string Slug { get; set; }
        /// <summary>
        /// Nội dung của slug (mô tả, giới thiệu,...)
        /// </summary>
        public string Content { get; set; }
        /// <summary>
        /// Thời gian tạo
        /// </summary>
        public DateTime CreatedDate { get; set; }
        /// <summary>
        /// Thời gian cập nhật
        /// </summary>
        public DateTime? UpdatedDate { get; set; }
        /// <summary>
        /// Id của category
        /// </summary>
        public Guid CategoryId { get; set; }

        public virtual Category Category { get; set; }
        public virtual ICollection<Producttag> Producttag { get; set; }
    }
}